name: Docker Image CI

on:
  push:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Build Image
        env:
          ENV_VAR: ${{ secrets.REACT_APP_SERVERLESS_URL }}
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
        run: |
          docker build --build-arg env_var=$ENV_VAR -t $DOCKER_USER/aws-serverless:latest .
      - name: Push to DockerHub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
        run: |
          docker push $DOCKER_USER/practise-docker-repository:latest
